version: "3.9"

services:
  web:
    build: . 
    command: python /projects/blogsite/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/projects/blogsite
    ports: 
      - 8000:8000
    depends_on:
      - db
    environment:   
    # if a dollar sign appears in the key - ensure to place another dollar sign to avoid errors with docker assigning variables
      - "DJANGO_SECRET_KEY=django-insecure-(n1rf_6i097*+2e$$e)7deh59ohu=*&6!_ot=e56uudli%$$qn%d"
      - "DJANGO_DEBUG=True"
  
  db:
    image: postgres:13
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    
volumes:
  postgres_data:
